HalloDoc Project/Controllers/ProviderController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using BAL.Interfaces;
using BAL.Interfaces.IProvider;
using DAL.DataContext;
using DAL.DataModels;
using DAL.ViewModels;
using DocumentFormat.OpenXml.Office2019.Drawing.Model3D;
using DocumentFormat.OpenXml.Spreadsheet;
using HalloDoc_Project.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Build.Framework;
using Rotativa.AspNetCore;
using System.Security.Policy;
using static HalloDoc_Project.Extensions.Enumerations;


namespace HalloDoc_Project.Controllers
{
    [CustomAuthorize("Physician")]

    public class ProviderController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IAdminActions _adminActions;
        private readonly IAdminTables _adminTables;
        private readonly IEmailService _emailService;
        private readonly IWebHostEnvironment _environment;
        private readonly IFileOperations _fileOperations;
        private readonly INotyfService _notyf;
        private readonly IEncounterForm _encounterForm;
        private readonly ICreateEditProviderRepo _createEditProviderRepo;
        private readonly IPasswordHasher _passwordHasher;
        public ProviderController(ApplicationDbContext context, IAdminActions adminActions, IAdminTables adminTables, IEmailService emailService, IWebHostEnvironment environment, IFileOperations fileOperations, INotyfService notyf, IEncounterForm encounterForm, ICreateEditProviderRepo createEditProviderRepo, IPasswordHasher passwordHasher)
        {
            _context = context;
            _adminActions = adminActions;
            _adminTables = adminTables;
            _emailService = emailService;
            _environment = environment;
            _fileOperations = fileOperations;
            _notyf = notyf;
            _encounterForm = encounterForm;
            _createEditProviderRepo = createEditProviderRepo;
            _passwordHasher = passwordHasher;
        }

        public IActionResult ProviderDashboard()
        {
            try
            {
                var id = HttpContext.Session.GetString("AspnetuserId");
                AdminDashboardViewModel model = _adminTables.ProviderDashboard(id);
                return View(model);
            }
            catch
            {
                HttpContext.Session.Clear();
                Response.Cookies.Delete("jwt");
                _notyf.Error("Exception in Provider Dashboard.");
                return RedirectToAction("login_page", "Guest");
            }
        }
        public DashboardFilter SetDashboardFilterValues(int page, int region, int type, string search)
        {
            int pagesize = 5;
            int pageNumber = 1;
            if (page > 0)
            {
                pageNumber = page;
            }
            DashboardFilter filter = new()
            {
                PatientSearchText = search,
                RegionFilter = region,
                RequestTypeFilter = type,
                pageNumber = pageNumber,
                pageSize = pagesize,
                page = page,
            };
            return filter;
        }
        public IActionResult GetNewTable(int page, int region, int type, string search)
        {
            try
            {

                var aspnetuserid = HttpContext.Session.GetString("AspnetuserId");
                Physician physician = _context.Physicians.FirstOrDefault(x => x.Aspnetuserid == aspnetuserid);
                var filter = SetDashboardFilterValues(page, region, type, search);
                AdminDashboardViewModel model = _adminTables.ProviderNewTable(filter, physician.Physicianid);
                model.currentPage = filter.pageNumber;

                return View("PartialTables/ProviderNewTable", model);
            }
            catch
            {

                _notyf.Error("Exception in fetching new table get.");
                return RedirectToAction("ProviderDashboard");
            }
        }
        public IActionResult GetPendingTable(int page, int region, int type, string search)
        {
            try
            {
                var aspnetuserid = HttpContext.Session.GetString("AspnetuserId");
                Physician physician = _context.Physicians.FirstOrDefault(x => x.Aspnetuserid == aspnetuserid);
                var filter = SetDashboardFilterValues(page, region, type, search);
                AdminDashboardViewModel model = _adminTables.ProviderPendingTable(filter, physician.Physicianid);
                model.currentPage = filter.pageNumber;

                return PartialView("PartialTables/ProviderPendingTable", model);
            }
            catch
            {

                _notyf.Error("Exception in fetching pending table get.");
                return RedirectToAction("ProviderDashboard");
            }
        }
        public IActionResult GetActiveTable(int page, int region, int type, string search)
        {
            try
            {

                var aspnetuserid = HttpContext.Session.GetString("AspnetuserId");
                Physician physician = _context.Physicians.FirstOrDefault(x => x.Aspnetuserid == aspnetuserid);
                var filter = SetDashboardFilterValues(page, region, type, search);
                AdminDashboardViewModel model = _adminTables.ProviderActiveTable(filter, physician.Physicianid);
                model.currentPage = filter.pageNumber;

                return PartialView("PartialTables/ProviderActiveTable", model);
            }
            catch
            {
                _notyf.Error("Exception in fetching active table get.");
                return RedirectToAction("ProviderDashboard");
            }
        }
        public IActionResult GetConcludeTable(int page, int region, int type, string search)
        {
            try
            {
                var aspnetuserid = HttpContext.Session.GetString("AspnetuserId");
                Physician physician = _context.Physicians.FirstOrDefault(x => x.Aspnetuserid == aspnetuserid);
                var filter = SetDashboardFilterValues(page, region, type, search);
                AdminDashboardViewModel model = _adminTables.ProviderConcludeTable(filter, physician.Physicianid);
                model.currentPage = filter.pageNumber;

                return PartialView("PartialTables/ProviderConcludeTable", model);
            }

            catch
            {
                _notyf.Error("Exception in fetching coclude table get.");
                return RedirectToAction("ProviderDashboard");
            }
        }
        public IActionResult AcceptCase(int requestid)
        {
            try
            {
                _adminActions.ProviderAcceptCase(requestid);
                return RedirectToAction("ProviderDashboard");
            }
            catch
            {
                _notyf.Error("Exception in accepting the case.");
                return RedirectToAction("ProviderDashboard");
            }
        }
        public IActionResult ProviderViewCase(int requestid)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    ViewCaseViewModel vc = _adminActions.ViewCaseAction(requestid);
                    return View("ActionViews/ProviderViewCase", vc);
                }
                return View("ActionViews/ProviderViewCase");
            }
            catch
            {
                _notyf.Error("Exception in Provider View Case.");
                return RedirectToAction("ProviderDashboard");
            }
        }
        public IActionResult ProviderViewNotes()
        {
            return View("ActionViews/ProviderViewNotes");
        }
        [HttpPost]
        public IActionResult SendAgreement(int RequestId, string PhoneNo, string email)
        {
            try
            {

                if (ModelState.IsValid)
                {
                    var AgreementLink = Url.Action("ReviewAgreement", "Guest", new { ReqId = RequestId }, Request.Scheme);
                    _emailService.SendAgreementLink(RequestId, AgreementLink, email);
                    _notyf.Success("Agreement link sent to user.");
                    return RedirectToAction("AdminDashboard", "Guest");
                }
                return View();
            }
            catch
            {
                _notyf.Error("Exception in Sending agreement.");
                return RedirectToAction("ProviderDashboard");
            }
        }
        #region Send Link
        [HttpPost]
        public void SendLink(string FirstName, string LastName, string Email)
        {
            try
            {
                var WebsiteLink = Url.Action("patient_submit_request_screen", "Guest", new { }, Request.Scheme);
                _emailService.SendEmailWithLink(FirstName, LastName, Email, WebsiteLink);
                _notyf.Success("Link sent.");
            }
            catch
            {
                _notyf.Error("Exception in accepting the case.");

            }
        }
        #endregion

        #region Create Request

        public IActionResult CreateRequestProviderDashboard()
        {
            try
            {

                CreateRequestViewModel model = new CreateRequestViewModel()
                {
                    Regions = _context.Regions.ToList(),
                };
                return View(model);
            }
            catch
            {
                _notyf.Error("Exception in Create request provider dashboard.");
                return RedirectToAction("ProviderDashboard");
            }
        }
        [HttpPost]
        [RoleAuthorize((int)AllowMenu.AdminDashboard)]
        public IActionResult CreateRequestProviderDashboard(CreateRequestViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _adminActions.CreateRequestFromAdminDashboard(model);

HalloDoc Project/Views/Provider/ActionViews/EncounterFormFinalizeView.cshtml
@model EncounterFormViewModel;
@{
    Layout = null;
}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Encounter Form Details</title>
    <style>
        * {
            font-family: 'Arial', sans-serif;
        }

        body {
            margin: 0;
            padding: 0;
        }

        .encounterForm {
            background-color: #fff;
            border: 2px solid #10bce9;
            border-radius: 25px;
            margin: 20px;
            padding: 20px;
            max-width: 800px;
            margin: auto;
        }

        h1 {
            color: #10bce9;
            font-family: poppins;
            font-size: 28px;
            margin-bottom: 20px;
        }

        .details {
            padding: 10px;
        }

        .data {
            margin-bottom: 15px;
            border: 2px solid;
            padding: 15px;
            border-radius: 8px;
            background-color: #f9f9f9;
            border: 1px solid #c7c7c7;
        }

            .data span {
                font-weight: bold;
                color: #555;
            }

        .followup {
            color: #10bce9;
        }
    </style>
</head>
<body>
    <div class="encounterForm h-100">
        <h1>Encounter Form Details</h1>
        <div class="details">
            <div class="data">
                <span>First Name: </span> @Model.FirstName
            </div>

            <div class="data">
                <span>Last Name: </span> @Model.LastName
            </div>

            <div class="data">
                <span>Location: </span> @Model.Location
            </div>

            <div class="data">
                <span>Date of Birth: </span> @Model.DateOfBirth
            </div>

            <div class="data">
                <span>Date of Request: </span> @Model.Date
            </div>

            <div class="data">
                <span>Email: </span> @Model.Email
            </div>

            <div class="data">
                <span>History of Present Illness or Injury: </span> @Model.IllnessHistory
            </div>

            <div class="data">
                <span>Medical History: </span> @Model.MedicalHistory
            </div>

            <div class="data">
                <span>Medications: </span> @Model.Medications
            </div>

            <div class="data">
                <span>Allergies: </span> @Model.Allergies
            </div>

            <div class="data">
                <span>Temp: </span> @Model.Temperature
            </div>

            <div class="data">
                <span>HR: </span> @Model.HR
            </div>

            <div class="data">
                <span>RR: </span> @Model.RR
            </div>

            <div class="data">
                <span>Blood Pressure (Diastolic): </span> @Model.BPLow
            </div>

            <div class="data">
                <span>Blood Pressure (Systolic): </span> @Model.BPHigh
            </div>

            <div class="data">
                <span>O2: </span> @Model.O2
            </div>

            <div class="data">
                <span>HEENT: </span> @Model.heent
            </div>

            <div class="data">
                <span>Pain: </span> @Model.Pain
            </div>

            <div class="data">
                <span>CV: </span> @Model.cv
            </div>

            <div class="data">
                <span>Chest: </span> @Model.chest
            </div>

            <div class="data">
                <span>Abdomen: </span> @Model.abd
            </div>

            <div class="data">
                <span>Extremities: </span> @Model.extr
            </div>

            <div class="data">
                <span>Skin: </span> @Model.skin
            </div>

            <div class="data">
                <span>Neuro: </span> @Model.neuro
            </div>

            <div class="data">
                <span>Other: </span> @Model.other
            </div>

            <div class="data">
                <span>Diagnosis: </span> @Model.diagnosis
            </div>

            <div class="data">
                <span>Treatment Plan: </span> @Model.treatmentPlan
            </div>

            <div class="data">
                <span>Medications Dispensed: </span> @Model.MedicationsDispensed
            </div>

            <div class="data">
                <span>Procedures: </span> @Model.procedures
            </div>

            <div class="data followup">
                <span>Follow Up Frequency: </span> @Model.followUps
            </div>
        </div>
    </div>
</body>
</html>

HalloDoc Project/Views/Provider/ActionViews/ProviderConcludeCare.cshtml
@model ViewUploadsViewModel
@{
    Layout = "_ProviderDashboardLayout";
    ViewData["Title"] = "Conclude Care";

}
<div class="container">
    <div class="row">
        <div class="col my-4 d-flex justify-content-between">
            <h2>Conclude Care</h2>
            <button type="button" class="btn btn-outline-info" onclick="history.back()">
                <svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 -960 960 960" width="24" fill="currentColor">
                    <path d="m142-480 294 294q15 15 14.5 35T435-116q-15 15-35 15t-35-15L57-423q-12-12-18-27t-6-30q0-15 6-30t18-27l308-308q15-15 35.5-14.5T436-844q15 15 15 35t-15 35L142-480Z" />
                </svg>
                Back
            </button>
        </div>
    </div>
    <div class="container mb-5 p-2 pb-5 request_form shadow-lg px-4">
        <small>Patient Name</small>
        <div class="d-flex align-items-center">
            <h4 class="text-info pe-1">@Model.Patientname</h4>
            <h6 class="">(@Model.ConfirmationNo)</h6>
        </div>
        <h5 class="my-3">Encounter Form</h5>
        <form method="post" enctype="multipart/form-data" >
            <div class="row">
                <div class="mb-3">
                    <input asp-for="RequestID" hidden />
                    <input class="form-control" asp-for="File" accept=".pdf" type="file" id="file_input_id" style="opacity:0;height:0;">

                    <div class="input-group mb-3">
                        <input type="text" id='text_input_id' class="form-control" placeholder="Select File" style="caret-color: transparent" autocomplete="off">
                        <div>
                            <button for="text_input_id" type="submit" class="ms-1 btn-info btn text-white">Upload</button>
                        </div>
                    </div>

                </div>
            </div>
        </form>
        <table class="table">
            <colgroup>
                <col style="width: 80%;">
                <col style="width: 20%;">
            </colgroup>
            <thead>
                <tr>
                    <th>Documents</th>
                    <th scope="col">Actions</th>
                </tr>
            </thead>
            <tbody>
                @if (Model.Requestwisefiles.Count == 0)
                {
                    <tr>
                        <td>
                            <div class="d-flex justify-content-center align-items-center text-muted">No Data Available</div>
                        </td>
                    </tr>
                }
                else
                {
                    @for (int i = 0; i < Model.Requestwisefiles.Count; i++)
                    {
                        @if (Model.Requestwisefiles[i].Isdeleted != true)
                        {
                            <tr>
                                <td>
                                    <svg height="20px" width="20px" version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 309.267 309.267" xml:space="preserve"><g>
                                    <path style="fill:#E2574C;" d="M38.658,0h164.23l87.049,86.711v203.227c0,10.679-8.659,19.329-19.329,19.329H38.658 c-10.67,0-19.329-8.65-19.329-19.329V19.329C19.329,8.65,27.989,0,38.658,0z" />
                                    <path style="fill:#B53629;" d="M289.658,86.981h-67.372c-10.67,0-19.329-8.659-19.329-19.329V0.193L289.658,86.981z" />
                                    <path style="fill:#FFFFFF;" d="M217.434,146.544c3.238,0,4.823-2.822,4.823-5.557c0-2.832-1.653-5.567-4.823-5.567h-18.44 c-3.605,0-5.615,2.986-5.615,6.282v45.317c0,4.04,2.3,6.282,5.412,6.282c3.093,0,5.403-2.242,5.403-6.282v-12.438h11.153 c3.46,0,5.19-2.832,5.19-5.644c0-2.754-1.73-5.49-5.19-5.49h-11.153v-16.903C204.194,146.544,217.434,146.544,217.434,146.544z M155.107,135.42h-13.492c-3.663,0-6.263,2.513-6.263,6.243v45.395c0,4.629,3.74,6.079,6.417,6.079h14.159 c16.758,0,27.824-11.027,27.824-28.047C183.743,147.095,173.325,135.42,155.107,135.42z M155.755,181.946h-8.225v-35.334h7.413 c11.221,0,16.101,7.529,16.101,17.918C171.044,174.253,166.25,181.946,155.755,181.946z M106.33,135.42H92.964 c-3.779,0-5.886,2.493-5.886,6.282v45.317c0,4.04,2.416,6.282,5.663,6.282s5.663-2.242,5.663-6.282v-13.231h8.379 c10.341,0,18.875-7.326,18.875-19.107C125.659,143.152,117.425,135.42,106.33,135.42z M106.108,163.158h-7.703v-17.097h7.703 c4.755,0,7.78,3.711,7.78,8.553C113.878,159.447,110.863,163.158,106.108,163.158z" /></g></svg>
                                    @Model.Requestwisefiles[i].Filename.Split('$')[1]
                                </td>
                                <td>
                                    <a class="btn btn-outline-info" href="/Content/@Model.Requestwisefiles[i].Filename" id="@i" download>
                                        <svg xmlns="http://www.w3.org/2000/svg" width="25px" height="25px" fill="currentcolor" class="bi bi-cloud-arrow-down" viewBox="0 0 16 16">
                                            <path fill-rule="evenodd" d="M7.646 10.854a.5.5 0 0 0 .708 0l2-2a.5.5 0 0 0-.708-.708L8.5 9.293V5.5a.5.5 0 0 0-1 0v3.793L6.354 8.146a.5.5 0 1 0-.708.708z" />
                                            <path d="M4.406 3.342A5.53 5.53 0 0 1 8 2c2.69 0 4.923 2 5.166 4.579C14.758 6.804 16 8.137 16 9.773 16 11.569 14.502 13 12.687 13H3.781C1.708 13 0 11.366 0 9.318c0-1.763 1.266-3.223 2.942-3.593.143-.863.698-1.723 1.464-2.383m.653.757c-.757.653-1.153 1.44-1.153 2.056v.448l-.445.049C2.064 6.805 1 7.952 1 9.318 1 10.785 2.23 12 3.781 12h8.906C13.98 12 15 10.988 15 9.773c0-1.216-1.02-2.228-2.313-2.228h-.5v-.5C12.188 4.825 10.328 3 8 3a4.53 4.53 0 0 0-2.941 1.1z" />
                                        </svg>
                                    </a>
                                </td>
                            </tr>
                        }
                    }
                }
            </tbody>
        </table>
        <hr />
        <h5 class="my-3">Provider Notes</h5>
        <form method="post" asp-action="ConcludeCare" asp-controller="Provider">
            <input asp-for=@Model.RequestID hidden/>
            <div class="mb-3">
                <textarea class="form-control" id="ProviderNotesTextArea" rows="3" asp-for="ProviderNotes" placeholder="Enter notes"></textarea>
            </div>
            @if (Model.isFinalized)
            {
                <div class="text-end my-3">
                    <button class="btn btn-info" type="submit" >Conclude Care</button>
                </div>
            }
            else
            {
                <div class="text-end my-3">
                    <button class="btn btn-info" onclick="DoNotConclude()" type="button">Conclude Care</button>
                    <div class="d-none" id="validationForConclude">
                        <small class="text-danger">
                            Finalize the Encounter Form to conclude this case.
                        </small>
                    </div>
                </div>
            }
        </form>
    </div>
</div>


<script>
    function DoNotConclude() {
        var validation=document.getElementById("validationForConclude");
        validation.classList.remove("d-none");
    }
</script>

<script>
    // bind file-input-form click action to text-input-span
    $('#text_input_span_id').click(function () {
        $("#file_input_id").trigger('click');
    })

    // bind file-input-form click action to text-input-form
    $('#text_input_id').click(function () {
        $("#file_input_id").trigger('click');
    })

    // display file name in text-input-form
    $("#file_input_id").change(function () {
        $('#text_input_id').val(this.value.replace(/C:\\fakepath\\/i, ''))
    })

    $(document).ready(function () {
        $('#SelectAll').on('click', function () {
            if (this.checked) {
                $('.checkbox').each(function () {
                    this.checked = true;
                });
            } else {
                $('.checkbox').each(function () {
                    this.checked = false;
                });
            }
        });

        $('.checkbox').on('click', function () {
            if ($('.checkbox:checked').length == $('.checkbox').length) {
                $('#select_all').prop('checked', true);
            }
            else {
                $('#select_all').prop('checked', false);
            }
        });
    });
</script>
<script>
    $(document).ready(function () {
        $("#DeleteAll").click(function () {
            console.log("Deleteall clicked");
            $(".del").each(function () {
                console.log("hello")
                $(this).trigger();
            });
        });
    });
</script>

HalloDoc Project/Views/Provider/ActionViews/ProviderViewCase.cshtml
@model ViewCaseViewModel
@{
    Layout = "_ProviderDashboardLayout";
    ViewData["Title"] = "View Case";

}
<div class="container">
    <div class=" d-flex align-items-center  justify-content-between">
        <div class="d-flex align-items-center my-3">
            <h2>View Reservation  </h2>
            <div class="text-light p-2 px-3 bg-success mb-2 ms-2 " style="border-radius:25px">
                Patient
            </div>
        </div>
        <div class="">
            <button class="btn-outline-info btn mb-2">
                Back
            </button>
        </div>
    </div>
    <div class="shadow-lg p-3">
        <h5 class="">Patient Information</h5>
        <small class="mt-0 text-muted">
            Confirmation Number
        </small>
        <h5 class="text-info">
            @Model.confirmationNo
        </h5>
        <div class="form-group">
            <textarea class="form-control" asp-for="patientnotes" id="exampleFormControlTextarea1" disabled rows="3"></textarea>
            <hr class="color-light mb-0" />
        </div>
        <form>

            <div class="row">
                <div class="col-11 mt-4 col-sm-6 form-floating ">
                    <input type="text" asp-for="patientfirstname" placeholder="First Name" class="t  form-control border" id="fname" disabled>
                    <label for="fname" class="ms-2">First Name</label>

                </div>
                <div class="col-11 col-sm-6 mt-4 form-floating  ">
                    <input type="text" asp-for="patientlastname" placeholder="Last Name" class="t form-control border" id="lname" disabled>
                    <label for="lname" class="ms-2">Last Name</label>
                </div>
            </div>
            <div class="row ">
                <div class="col-11 col-sm-6  mt-4 form-floating">
                    <input type="date" asp-for="dob" placeholder="Date Of Birth" class="t form-control border" id="DOB" disabled>
                    <label for="DOB" class="ms-2">Date Of Birth</label>
                </div>
                <div class="col-11 col-sm-5 mt-4 form-floating ">
                    <div class="form-floating border ">
                        <input id="patient-phone" asp-for="patientphone" class="form-control" type="tel" name="phone1" disabled />
                    </div>
                </div>
                <div class="col-11 col-sm-1 mt-4 form-floating align-items-center d-flex">
                    <button class="btn btn-outline-info px-3 py-2 border" type="button">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-telephone-fill" viewBox="0 0 16 16">
                            <path fill-rule="evenodd" d="M1.885.511a1.745 1.745 0 0 1 2.61.163L6.29 2.98c.329.423.445.974.315 1.494l-.547 2.19a.68.68 0 0 0 .178.643l2.457 2.457a.68.68 0 0 0 .644.178l2.189-.547a1.75 1.75 0 0 1 1.494.315l2.306 1.794c.829.645.905 1.87.163 2.611l-1.034 1.034c-.74.74-1.846 1.065-2.877.702a18.6 18.6 0 0 1-7.01-4.42 18.6 18.6 0 0 1-4.42-7.009c-.362-1.03-.037-2.137.703-2.877z" />
                        </svg>
                    </button>
                </div>
            </div>

            <div class="row align-items-center">

                <div class="col-11 col-sm-6  mt-4 form-floating ">
                    <input type="email" asp-for="patientemail" class="form-control border" id="email" disabled>
                    <label for="email" class="ms-2">E-mail</label>
                </div>

            </div>

            <h4 class="mt-4">Location Information</h4>

            <div class="row align-items-center">

                <div class="col-md-6 col-12">
                    <div class="form-floating mt-3">
                        <input asp-for="region" class="form-control" placeholder="Leave a comment here" disabled
                               id="floatingTextarea2"></input>
                        <label for="floatingTextarea2">Region</label>
                    </div>
                </div>

                <div class="col-md-5 col-12">
                    <div class="form-floating mt-3">
                        <input asp-for="address" class="form-control" placeholder="Leave a comment here" disabled></input>
                        <label for="floatingTextarea2">Name/Address</label>
                    </div>
                </div>

                <div class="col-1 mt-3">

                    <button class="btn btn-outline-info align-items-center d-flex justify-content-center" type="button" style="color: #10bce9;">
                        <svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 -960 960 960" fill="#10bce9" width="24"><path d="M480-480q33 0 56.5-23.5T560-560q0-33-23.5-56.5T480-640q-33 0-56.5 23.5T400-560q0 33 23.5 56.5T480-480Zm0 294q122-112 181-203.5T720-552q0-109-69.5-178.5T480-800q-101 0-170.5 69.5T240-552q0 71 59 162.5T480-186Zm0 106Q319-217 239.5-334.5T160-552q0-150 96.5-239T480-880q127 0 223.5 89T800-552q0 100-79.5 217.5T480-80Zm0-480Z" /></svg>
                    </button>

                </div>

                <div class="col-md-6 col-12">

                    <div class="form-floating mt-3">

                        <input asp-for="rooms" class="form-control" placeholder="Leave a comment here" disabled
                               id="floatingTextarea2">
                        <label for="floatingTextarea2">Rooms(Optional)</label>

                    </div>

                </div>
                <div class="d-flex justify-content-end mt-3">
                    <a asp-controller="Provider" asp-action="ProviderViewNotes" class="btn py-2 px-4 ms-3" style="background-color: #10bce9; color: white;">
                        View Notes
                    </a>
                </div>
        </form>
    </div>
    @*-----------------------------------------------------------------------------------------------------------------------------------------------*@
    <script>
        var phoneInputField = document.querySelector("#patient-phone");
        var phoneInput = window.intlTelInput(phoneInputField, {
            utilsScript:
                "https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.8/js/utils.js",
        });
    </script>   